### ISSUE TITLE
Include config.json in this repository

### ISSUE THREAD

**Issue by ElonaFoobar** [ElonaFoobar/ElonaFoobar#143]
# Details

See also #141.

# Tasks

* [ ] Add `runtime/config.json`.
* [ ] Exclude `runtime/config.json` from `.gitignore`.
* [ ] Delete `runtime/config.json` from `README.md`.
