### ISSUE TITLE
Implement data.lua mod script for loading data

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#728]
# Details
Mods should be able to load data declared in their directory. On startup, a script `data.lua` could be run to gather the list of places that data can be found. If any directory is registered twice, it will be ignored. Validation isn't currently performed, but it could be in the future.

```lua
Registry.load("core", "chara", "data/chara.hcl")
Registry.load("core", "music", "data/music.hcl")
```

# Tasks

- [ ] Refactor `chara_chip` and `item_chip` to use `lion`.
- [ ] Store list of declared data files/types in `lua::registry_manager`.
- [ ] Implement loading of `data.lua` in the root of each mod, if it exists.
