### ISSUE TITLE
Migrate `item.lua` to new data format

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#729]
# Details
For compatibility with mods, items should be declared the same way as characters, through data files in `.hcl` format. This will allow the mod loading mechanism to pick them up, and attach a readable string ID to each.

# Tasks
- [ ] Create `item.hcl`.
- [ ] Add new string IDs for each item.
- [ ] Migrate `cat_db` for `item_data` to `lion`.
