### ISSUE TITLE
Make the loading of mods more user-friendly

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#738]
# Details
The current behavior of crashing the game on when a mod fails to load isn't very user-friendly. Instead there should be a list of mod load failures at the title screen, and the mod should not be counted as loaded. In the future, this could cause dependent mods to also not load if any dependencies fail to load.

# Tasks
- [ ] Convert `lion`/mod/data loading routines to return `result<T, E>`.
- [ ] Remove mods that fail to initialize/load data.
- [ ] Notify the user on startup if any mods fail to load during initialization/data loading.
