### ISSUE TITLE
Port English translation from omake EN, oo EN, and oo EN hack

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#750]
# Details

A few month ago, omake and omake overhaul were translated into English. I contacted to Doorknob, the main translator, and he allowed us to port the translation of omake and oo(including typo/bug fix in vanilla's English mode) to Elona foobar.

# Tasks

- [ ] Port translation, typo fix, and bug fix from omake EN.
- [ ] Port translation, typo fix, and bug fix from omake overhaul EN.
- [ ] Port translation, typo fix, and bug fix from omake overhaul EN hack.
- [ ] Add "Doorknob" to credit.

# Links

- omake EN: [English wiki page](http://elona.wikia.com/wiki/Omake) / [Download here](https://cdn.discordapp.com/attachments/410208644379049994/434133791817203732/elona_omake_en.exe)
- omake overhaul EN: [English wiki page](http://elona.wikia.com/wiki/Omake_overhaul) / [Download here](https://cdn.discordapp.com/attachments/410208644379049994/472908514377990174/omake_overhaul_EN.zip)
- omake overhaul EN hack: [Download here](https://cdn.discordapp.com/attachments/410208644379049994/475218270153211914/Elona_oo_English_hack_20180804.zip)

omake EN/oo EN are pure English-translated version of omake/oo. oo EN hack is a variant developed by me, and ports convenient stuffs from oo's variants(oomEx, oor, and oomSE).
